name: CI-CD-pipeline
on:
  push:  
    branches: [master]
jobs:
  Build:  
    runs-on: self-hosted     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build
        run: echo "Build is successful"
  Test:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run:  echo "Test is successful"
  Deploy:
    runs-on: self-hosted
    needs: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        shell: powershell
        run: echo "Deployment is successful"
